#pragma once

// ─────────────────────────────────────────────────────────────────────────────
// Cue list — ALBEDO  (43 min · 25fps)
// Varytec LED Theater Spot 50 3200K  (2-channel DMX mode)
// Julian Charrière · CORRER · Venice 2026
//
//   Fixture minimum visible threshold: DMX 22  (below = physically dark)
//   Floor glow = DMX 38.  Hard black = DMX 0 (final fade only).
//
// ── COMPOSITIONAL STRATEGY — HYBRID FOLLOW / COUNTERPOINT ──────────────────
//
//   Derived from per-second luma analysis of v02_260415_Albedo_Correr_Preview.mov
//   (see albedo_luma.csv / albedo_luma.png, generated by analyze_movie_luma.py)
//
//   Film character: nearly entirely dark (mean luma 8.5/255).
//   Bright events are isolated, brief, violent flares of reflected glacial light.
//   The film never exceeds 58% white.
//
//   COUNTERPOINT (lamp warm while film is dark):
//     The lamp glows and breathes during the long dark sections — a memory of
//     reflected sunlight, the albedo the glacier no longer has.
//
//   FOLLOW / DIP (lamp yields when film flares):
//     At the three major film bright events, the lamp pulls back sharply —
//     it does not compete. The room lets the image carry the brightness.
//     After each film flare fades, the lamp slowly recovers.
//
//   Film bright events (from luma analysis):
//     09:26   35/255  small flicker
//     14:05   68/255  medium flare
//     15:16   68/255  medium flare
//     21:01   76/255  building glow (67s)
//     22:58  133/255  *** FIRST MAJOR FLARE ***  peak 23:19
//     25:10   72/255  scattered surface light
//     25:57   69/255
//     27:08   64/255
//     35:17  107/255  *** SECOND MAJOR FLARE ***  peak 35:29
//     36:53  147/255  *** FILM ABSOLUTE PEAK ***  peak 37:02
//     37:09  106/255  afterglow
//     37:36  119/255  afterglow
//     38:18   86/255  afterglow fade
//
//   Long dark valleys (luma < 3):
//     00:00–09:22  (562s)  — lamp counterpoint, slow build
//     09:44–14:04  (260s)  — lamp counterpoint, mid-level
//     18:59–20:47  (108s)  — lamp at plateau, preparing for film flare
//     23:32–25:09  (97s)   — lamp recovering from dip
//     27:45–35:16  (451s)  *** LONGEST DARK ***  lamp apex here (counterpoint)
//     35:37–36:52  (75s)   — lamp retreating with the film
//     37:46–38:17  (31s)   — lamp dipping after film peak
//
//   DMX apex: 0:31:30 — lamp is brightest during the film's longest silence.
//
// ─────────────────────────────────────────────────────────────────────────────

#include "dmx_controller.h"
#include "../include/config.h"

#define V(d, s) \
    { {DMX_CH_MASTER,(d)}, {DMX_CH_STROBE,(s)} }, 2

static const DMXCue CUE_LIST[] = {

    // ── 0:00:00 — OPEN ──────────────────────────────────────────────────────
    //   Film: hard black. Lamp opens alone. Slow breath begins.
    { 0,  0,  0, 0,   8000, V( 38, 0) },   // 8s warm fade-in to floor (→ 0:00:08)

    // ── COUNTERPOINT ZONE 1 — 0:00–9:22  (film dark) ────────────────────────
    //   Long slow first breath. Three waves, gentle, spreading into the room.

    // Wave 1  (0:00:08 → 0:02:30)
    { 0,  0,  8, 0,  35000, V( 68, 0) },   // 35s slow rise (→ 0:00:43)
    { 0,  0, 43, 0,  22000, V( 88, 0) },   // 22s surge (→ 0:01:05)
    { 0,  1,  5, 0,  85000, V( 38, 0) },   // 85s long ebb to floor (→ 0:02:30)

    // Wave 2  (0:02:30 → 0:05:15)
    { 0,  2, 30, 0,  38000, V( 78, 0) },   // 38s rise (→ 0:03:08)
    { 0,  3,  8, 0,  22000, V(100, 0) },   // 22s surge (→ 0:03:30)
    { 0,  3, 30, 0, 105000, V( 38, 0) },   // 105s long ebb (→ 0:05:15)

    // Wave 3 — building  (0:05:15 → 0:09:22)
    { 0,  5, 15, 0,  40000, V( 88, 0) },   // 40s rise (→ 0:05:55)
    { 0,  5, 55, 0,  25000, V(118, 0) },   // 25s surge (→ 0:06:20)
    { 0,  6, 20, 0,  10000, V(108, 0) },   // 10s shoulder (→ 0:06:30)
    { 0,  6, 30, 0, 172000, V( 38, 0) },   // 172s ebb to floor (→ 0:09:22)

    // ── FILM FLICKER  09:26 (35/255) — lamp low, brief ──────────────────────
    //   Small flicker in film. Lamp at floor, barely moves.
    { 0,  9, 22, 0,  12000, V( 52, 0) },   // 12s slight rise during flicker (→ 0:09:34)
    { 0,  9, 34, 0,  26000, V( 38, 0) },   // 26s settle back (→ 0:10:00)

    // ── COUNTERPOINT ZONE 2 — 9:44–14:04  (film dark) ───────────────────────
    //   Wave 4: deeper, richer. Film has gone dark again for 4+ minutes.

    // Wave 4  (0:10:00 → 0:14:04)
    { 0, 10,  0, 0,  42000, V( 98, 0) },   // 42s rise (→ 0:10:42)
    { 0, 10, 42, 0,  25000, V(132, 0) },   // 25s surge (→ 0:11:07)
    { 0, 11,  7, 0,  12000, V(120, 0) },   // 12s shoulder (→ 0:11:19)
    { 0, 11, 19, 0, 165000, V( 38, 0) },   // 165s slow ebb (→ 0:14:04)

    // ── FILM FLARES  14:05–15:43 (68/255, 68/255) — lamp DIPS ───────────────
    //   Two medium film flares. Lamp steps back, lets film carry the light.
    { 0, 14,  4, 0,   4000, V( 28, 0) },   // 4s quick dip below floor (→ 0:14:08)
    { 0, 14,  8, 0,  95000, V( 38, 0) },   // 95s very slow recovery during flares (→ 0:15:43)

    // ── ZONE 3 — 15:49–18:53  (film mostly dark, small flickers) ────────────
    //   Wave 5: medium height, anticipating the coming film glow at 21:01.

    // Wave 5  (0:15:43 → 0:18:58)
    { 0, 15, 43, 0,  35000, V( 88, 0) },   // 35s rise (→ 0:16:18)
    { 0, 16, 18, 0,  22000, V(112, 0) },   // 22s surge (→ 0:16:40)
    { 0, 16, 40, 0,  10000, V(105, 0) },   // 10s shoulder (→ 0:16:50)
    { 0, 16, 50, 0, 128000, V( 38, 0) },   // 128s ebb (→ 0:18:58)

    // ── APPROACH  18:58–21:00  (film quiet, building film glow at 21:01) ─────
    //   Lamp holds low floor, letting the upcoming film flare dominate.
    { 0, 18, 58, 0,  62000, V( 50, 0) },   // 62s gentle breathing rise (→ 0:20:00)
    { 0, 20,  0, 0,  62000, V( 38, 0) },   // 62s settle back to floor (→ 0:21:02)

    // ── FILM GLOW  21:01–22:06 (76/255, 67s) — lamp dips gently ─────────────
    //   First sustained film glow. Lamp retreats slightly — not a compete.
    { 0, 21,  2, 0,  30000, V( 28, 0) },   // 30s dip to near-floor (→ 0:21:32)
    { 0, 21, 32, 0,  34000, V( 38, 0) },   // 34s slow recovery (→ 0:22:06)

    // ── FILM MAJOR FLARE  22:58–23:27 (133/255) — lamp DROPS HARD ────────────
    //   The brightest film event before 35:00. Lamp drops sharply — the room
    //   surrenders all light to the image. After the flare ends, slow return.
    { 0, 22,  6, 0,  30000, V( 62, 0) },   // 30s rise — building before we know it (→ 0:22:36)
    { 0, 22, 36, 0,  22000, V( 22, 0) },   // 22s decisive drop to threshold (→ 0:22:58) — film starts
    { 0, 22, 58, 0,  29000, V( 22, 0) },   // 29s hold at threshold during flare peak (→ 0:23:27)
    { 0, 23, 27, 0,  65000, V( 38, 0) },   // 65s slow recovery to floor (→ 0:24:32)

    // ── SCATTERED SURFACE LIGHT  25:10–27:44  (60–72/255) ───────────────────
    //   Several smaller film flares. Lamp holds low, minimal movement.
    { 0, 24, 32, 0,  38000, V( 55, 0) },   // 38s gentle rise (→ 0:25:10)
    { 0, 25, 10, 0,  34000, V( 38, 0) },   // 34s dip as film flickers (→ 0:25:44)
    { 0, 25, 44, 0,  30000, V( 52, 0) },   // 30s small recovery (→ 0:26:14)
    { 0, 26, 14, 0,  54000, V( 38, 0) },   // 54s settle (→ 0:27:08)
    { 0, 27,  8, 0,  37000, V( 38, 0) },   // 37s hold at floor through last flickers (→ 0:27:45)

    // ── ████ COUNTERPOINT APEX — 27:45–35:17 (451s, film's longest dark) ████
    //   The film goes completely dark for 7.5 minutes.
    //   This is the lamp's moment. Single long arc to full power.
    //   The lamp is the memory of all the light the glacier once held.

    // Approach: 27:45 → 29:30
    { 0, 27, 45, 0,  45000, V( 62, 0) },   // 45s floor to first third (→ 0:28:30)
    { 0, 28, 30, 0,  60000, V( 95, 0) },   // 60s steady climb (→ 0:29:30)

    // Rising arc: 29:30 → 31:30
    { 0, 29, 30, 0,  40000, V(128, 0) },   // 40s (→ 0:30:10)
    { 0, 30, 10, 0,  40000, V(162, 0) },   // 40s (→ 0:30:50)
    { 0, 30, 50, 0,  40000, V(198, 0) },   // 40s (→ 0:31:30)

    // ██ APEX  0:31:30 — DMX 235 ██
    { 0, 31, 30, 0,  25000, V(235, 0) },   // 25s to full power (→ 0:31:55)
    { 0, 31, 55, 0,  25000, V(228, 0) },   // 25s peak hold / shoulder (→ 0:32:20)

    // Descent: 32:20 → 35:17  (still film dark throughout)
    { 0, 32, 20, 0,  40000, V(195, 0) },   // 40s first step down (→ 0:33:00)
    { 0, 33,  0, 0,  50000, V(158, 0) },   // 50s (→ 0:33:50)
    { 0, 33, 50, 0,  50000, V(118, 0) },   // 50s (→ 0:34:40)
    { 0, 34, 40, 0,  37000, V( 72, 0) },   // 37s approaching the film flare (→ 0:35:17)

    // ── FILM SECOND MAJOR FLARE  35:17–35:35 (107/255) — lamp holds LOW ──────
    //   Film suddenly bright. Lamp holds low — doesn't fight it.
    { 0, 35, 17, 0,  18000, V( 38, 0) },   // 18s fast retreat to floor (→ 0:35:35)

    // ── FILM ABSOLUTE PEAK  36:53–38:33 (147/255) ────────────────────────────
    //   The film's brightest moment. Lamp is a ghost — near-threshold only.
    //   After the peak the lamp rises once more as the film fades away.
    { 0, 35, 35, 0,  38000, V( 28, 0) },   // 38s dip below floor approaching film peak (→ 0:36:13)
    { 0, 36, 13, 0,  40000, V( 22, 0) },   // 40s hold at threshold — film peaks here (→ 0:36:53)
    { 0, 36, 53, 0,  60000, V( 22, 0) },   // 60s threshold hold through film's absolute peak (→ 0:37:53)
    { 0, 37, 53, 0,  25000, V( 38, 0) },   // 25s return to floor as film fades (→ 0:38:18)

    // ── FILM AFTERGLOW  38:18–38:33 (86/255) — lamp still low ───────────────
    { 0, 38, 18, 0,  15000, V( 28, 0) },   // 15s slight dip during last afterglow (→ 0:38:33)

    // ── CLOSING — 38:33–42:32  (film dark) ──────────────────────────────────
    //   Film has gone dark. Lamp exhales its last warmth.
    //   One slow final wave, descending.

    // Final wave  (0:38:33 → 0:41:30)
    { 0, 38, 33, 0,  52000, V( 82, 0) },   // 52s rise — last warmth (→ 0:39:25)
    { 0, 39, 25, 0,  25000, V( 98, 0) },   // 25s peak (→ 0:39:50)
    { 0, 39, 50, 0,  15000, V( 90, 0) },   // 15s shoulder (→ 0:40:05)
    { 0, 40,  5, 0, 145000, V( 38, 0) },   // 145s very long ebb back to floor (→ 0:42:32)

    // ── FINAL FADE TO BLACK  (42:32 – 43:20) ────────────────────────────────
    { 0, 42, 32, 0,  48000, V(  0, 0) },   // 48s fade to black (→ 0:43:20)
    { 0, 43,  0, 0,      0, V(  0, 0) },   // safety snap at loop end

};  // END CUE_LIST

#undef V

static const uint16_t CUE_COUNT = sizeof(CUE_LIST) / sizeof(CUE_LIST[0]);
// Varytec LED Theater Spot 50 3200K  (2-channel DMX mode)
// Julian Charrière · CORRER · Venice 2026
//
//   Fixture: 4× Varytec LED Theater Spot 50, 3200K warm white, 2-ch DMX mode.
//            All 4 at DMX address 001 — all fire identically.
//   CH 1 = Master dimmer  ( 0 = off, 255 = full )
//   CH 2 = Strobe         ( 0 = off, 4 = slowest, 255 = fastest )
//
//   !! IMPORTANT — fixture minimum visible threshold !!
//      The Varytec LED Theater Spot 50 COB LED requires ≥ DMX 22 on CH1
//      before any light is visible. Below 22 the lamp is physically dark.
//      → trough floor = DMX 40 (~16%) — always visibly glowing warm
//      → DMX 0 only at the very final fade-out
//
// Format: { HH, MM, SS, FF, fadeMs, { {ch,val}, ... }, numChannels }
//
// ── COMPOSITION — ALBEDO ────────────────────────────────────────────────────
//
//   ALBEDO: the fraction of incident light reflected by a surface.
//   Here: reflected sunlight inside a white body — glacier, ice, snow.
//   The surface always holds some light. It breathes. It never fully dies.
//
//   20 asymmetric sea-waves, continuous from 0:00:00.
//   No hard cuts. No strobes. No silence. No darkness.
//
//   Wave shape: asymmetric — fast flood (~25%), slow ebb (~65%).
//   Each wave has 4 control points: rise → surge → shoulder → ebb.
//   Floor: DMX 40 throughout (well above fixture threshold).
//   Apex break: snaps to floor (DMX 40), not to black.
//
//   Arc:
//     0:00 –  6:12  Awakening  — floor 40, peaks 78→102
//     6:12 – 15:17  Growing    — floor 40, peaks 102→142
//    15:17 – 24:55  Building   — floor 40, peaks 142→185
//    24:55 – 29:45  Apex zone  — floor 40, peaks 185→235 (92%)
//                              apex REACHED at 0:27:58 — break to DMX 40
